
import Navbar from "../components/Menu";
import "./new.css";
import Link from 'next/link'

export const metadata = {
  title: "ChartOB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
